name: .NET Core

on: [push, pull_request]

jobs:
  build:
    name: Build and test

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        framework: ['netcoreapp3.1', 'net50']
    steps:

    - name: Check out code onto host
      uses: actions/checkout@master

    - name: Setup .Net 3.1
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: '3.1.x' # SDK Version to use.
      if: matrix.framework == 'netcoreapp3.1'

    - name: Setup .Net 5.0
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: '5.0.x' # SDK Version to use.
      if: matrix.framework == 'net50'

    - name: Dotnet info
      run: |
        dotnet --version
        dotnet --info

    - name: Clear nuget cache
      run: |
        dotnet clean
        dotnet nuget locals all --clear

    - name: Build and Run unit tests
      run: |
        dotnet restore
        dotnet test --no-restore --verbosity normal --framework=${{ matrix.framework }}

    #dotnet build --configuration Release --no-restore --framework ${{ matrix.framework }}


  #buildMatrix:

  #  runs-on: windows-latest
  #  strategy:
  #    matrix:
  #      dotnet-version: [ '3.1.x', '5.0.x' ]
  #  steps:
  #  - uses: actions/checkout@master
  #  - name: Setup .NET Core ${{ matrix.dotnet-version }}
  #    uses: actions/setup-dotnet@v1.8.0
  #    with:
  #      dotnet-version: ${{ matrix.dotnet-version }}
  #  - name: Install dependencies
  #    run: dotnet restore
  #  - name: Build
  #    run: dotnet build --configuration Release --no-restore --framework ${{ matrix.framework }}
  #  - name: Test
  #    run: dotnet test --no-restore --verbosity normal
