name: .NET Core

on: [push, pull_request]

jobs:
  build:
    name: Build and test

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        framework: ['netcoreapp3.1', 'net50']
    steps:

    - name: Check out code onto host
      uses: actions/checkout@master

    - name: Setup .Net 3.1
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: '3.1.x' # SDK Version to use.
      if: matrix.framework == 'netcoreapp3.1'

    - name: Setup .Net 5.0
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: '5.0.x' # SDK Version to use.
      if: matrix.framework == 'net50'

    - name: Dotnet info
      run: |
        dotnet --version
        dotnet --info

    - name: Clear nuget cache
      run: |
        dotnet clean
        dotnet nuget locals all --clear

    - name: Dotnet restore
      run: |
        dotnet restore

    - name: Build and Run unit tests
      run: |
        dotnet test --no-restore --configuration Release --verbosity normal --framework=${{ matrix.framework }}

  #benchmark:
  #  name: Run benchmarks

  #  runs-on: ${{ matrix.os }}
  #  needs: build
  #  steps:
    - name: Run Benchmarks
      run: |
        dotnet run --no-restore --configuration Release --verbosity normal --framework=${{ matrix.framework }} --project ./tests/CSRakowski.Parallel.Benchmarks/